sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t db .
  - docker run --detach --name db db

script:
  # this is an ps style ping, that will only run if the service is running
  - docker ps
  # inspect for running state.
  - docker inspect -f {{.State.Running}} db
  # top the container, which returns 1 if not running
  - docker top db